POST http://127.0.0.1:8080/api/cars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wdGltYWNyb3MiLCJpYXQiOjE2ODMxOTQ2NzQsImV4cCI6MTY4MzE5ODI3NH0.Vz6auYBj0HMlGixm8JECjZJdDhgnoTpGwuqSz6FwlwQ
Content-Type: application/json

{
  "brand": "Ford",
  "model": "Mustang GT 4",
  "color": "red",
  "year": 1965,
  "price": 211
}
