DELETE http://localhost:8080/api/cars/645383d6d931cb76666ba298
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wdGltYWNyb3MiLCJpYXQiOjE2ODMxOTQ2NzQsImV4cCI6MTY4MzE5ODI3NH0.Vz6auYBj0HMlGixm8JECjZJdDhgnoTpGwuqSz6FwlwQ
