GET http://127.0.0.1:8080/api/cars?filter[brand]=Ford&filter[1]=1223
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wdGltYWNyb3MiLCJpYXQiOjE2ODMyODc4NTAsImV4cCI6MTY4MzI5MTQ1MH0.7qoGTXnn5eAV4Dtypd1e0TdMQ_dvqHJX8Q6p1_XDGwQ
