GET http://localhost:8080/api/cars/644cad1355f7d66c05e63d6c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wdGltYWNyb3MiLCJpYXQiOjE2ODMxOTc1NDYsImV4cCI6MTY4MzE5NzU0N30.C_YNwRWp0kD-pkXUK3IxL3n6BnPwU8lFCEq7AcOmIJg
