PATCH http://localhost:8080/api/cars/644e2b352dc9a980c7cbcbbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wdGltYWNyb3MiLCJpYXQiOjE2ODMxOTQ2NzQsImV4cCI6MTY4MzE5ODI3NH0.Vz6auYBj0HMlGixm8JECjZJdDhgnoTpGwuqSz6FwlwQ
Content-Type: application/json

{
  "brand": "Ford",
  "model": "Mustang GT 2",
  "year": 2017,
  "color": "blue",
  "price": 350
}
